import { GoogleGenerativeAI } from '@google/generative-ai'
import fs from 'fs'
import path from 'path'
import { prisma } from './prisma'
import { logSystem } from './logger'

// Initialize Gemini with key rotation
const API_KEYS = (process.env.GOOGLE_API_KEY || 'dummy').split(',');
let currentKeyIndex = 0;

function getGenAI() {
  const key = API_KEYS[currentKeyIndex];
  currentKeyIndex = (currentKeyIndex + 1) % API_KEYS.length;
  // console.log(`Using API Key index: ${currentKeyIndex} (ending in ...${key.slice(-4)})`);
  return new GoogleGenerativeAI(key);
}

export interface ProcessedArticle {
  title: string
  content: string
  slug: string
  metaDesc: string
  qualityScore: number
  category: string
  insight: string
  imageUrl?: string
  imagePrompt?: string
}

const DEFAULT_PROMPT_TEMPLATE = `
      You are a professional journalist and SEO expert.
      Process this news article:
      Title: \${originalTitle}
      Content: \${originalContent}

      Tasks:
      1. Summarize in 5 points.
      2. Rewrite in neutral journalistic tone (max 600 words).
      3. Add insight paragraph.
      4. Generate SEO Title, Slug, Meta Desc.
      5. Classify into ONE of these categories: "Technology", "Business", "Sports", "Health", "Entertainment", "Politics", "General".
      6. Score quality (0-100).
      7. Create a short, descriptive English prompt for generating an image relevant to this news (max 15 words).

      Return JSON ONLY with this structure:
      { "title": "", "content": "", "slug": "", "metaDesc": "", "category": "", "qualityScore": 0, "insight": "", "imagePrompt": "" }

      IMPORTANT:
      - "qualityScore" MUST be between 80 and 95.
      - "content" MUST be HTML formatted (use <h2>, <p>, <ul>).
      - "category" MUST be one of the listed categories.
`;

async function downloadImage(url: string, filename: string): Promise<string | null> {
  try {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`Failed to fetch image: ${response.statusText}`);
    
    const arrayBuffer = await response.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    
    // Ensure directory exists
    const dir = path.join(process.cwd(), 'public', 'images', 'articles');
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    
    const filepath = path.join(dir, filename);
    fs.writeFileSync(filepath, buffer);
    
    return `/images/articles/${filename}`;
  } catch (error) {
    console.error("Image Download Error:", error);
    return null;
  }
}

async function generateImage(prompt: string, slug: string): Promise<string | null> {
  try {
    // Pollinations.ai URL
    const encodedPrompt = encodeURIComponent(prompt);
    const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}`;
    
    const filename = `${slug}-${Date.now()}.jpg`;
    return await downloadImage(imageUrl, filename);
  } catch (error) {
    console.error("Image Generation Error:", error);
    return null;
  }
}

export async function processArticleWithAI(originalContent: string, originalTitle: string): Promise<ProcessedArticle> {
  // Mock implementation if no API key
  if (!process.env.GOOGLE_API_KEY || process.env.GOOGLE_API_KEY === 'dummy') {
    console.log("Using Mock AI for:", originalTitle)
    const slug = originalTitle
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') + '-' + Date.now().toString().slice(-4);
      
    return {
      title: `(Rewritten) ${originalTitle}`,
      content: `
        <p><strong>Summary:</strong> This is a summary of the article about ${originalTitle}.</p>
        <p><strong>Rewrite:</strong> Here is the rewritten content. The original article discussed various points which have been rephrased here for uniqueness and clarity.</p>
        <p><strong>Insight:</strong> This event is significant because it demonstrates the capabilities of the system.</p>
      `,
      slug: slug,
      metaDesc: `A rewritten version of ${originalTitle} covering key aspects and insights.`,
      category: "General",
      qualityScore: 85, // Auto publish
      insight: "Mock insight generated by system.",
      imageUrl: "https://placehold.co/600x400?text=Mock+Image"
    }
  }

  try {
    // Fetch dynamic prompt
    const promptSetting = await prisma.systemSetting.findUnique({
        where: { key: 'ai_prompt_template' }
    });

    const template = promptSetting?.value || DEFAULT_PROMPT_TEMPLATE;
    const prompt = template
        .replace(/\${originalTitle}/g, originalTitle)
        .replace(/\${originalContent}/g, originalContent.substring(0, 5000));

    // Model Fallback Logic
    const modelsToTry = ["gemini-1.5-flash", "gemini-1.5-flash-001", "gemini-1.0-pro", "gemini-pro"];
    let result;
    let lastError;

    for (const modelName of modelsToTry) {
        try {
            const model = getGenAI().getGenerativeModel({ model: modelName });
            
            // Retry logic for 429 (Quota)
            let attempts = 0;
            const maxAttempts = 3;
            while (attempts < maxAttempts) {
                try {
                    result = await model.generateContent(prompt);
                    break; // Success
                } catch (e: any) {
                    if (e.message && (e.message.includes("429") || e.status === 429)) {
                        attempts++;
                        console.log(`[${modelName}] Quota exceeded (429). Retrying in ${attempts * 2}s...`);
                        await new Promise(resolve => setTimeout(resolve, attempts * 2000));
                        currentKeyIndex = (currentKeyIndex + 1) % API_KEYS.length;
                    } else {
                        throw e; // Throw to model loop
                    }
                }
            }
            
            if (result) break; // Success

        } catch (e: any) {
            console.warn(`Model ${modelName} failed: ${e.message}`);
            lastError = e;
            // Continue to next model
        }
    }

    if (!result) throw lastError || new Error("All models failed");

    const response = await result.response;
    const text = response.text();
    
    // Improved JSON Extraction
    let jsonString = text.replace(/```json/g, '').replace(/```/g, '').trim();
    
    // If text contains extra narrative, try to extract just the JSON object
    const firstBrace = jsonString.indexOf('{');
    const lastBrace = jsonString.lastIndexOf('}');
    
    if (firstBrace !== -1 && lastBrace !== -1) {
        jsonString = jsonString.substring(firstBrace, lastBrace + 1);
    }

    let data;
    try {
        data = JSON.parse(jsonString);
    } catch (parseError: any) {
        console.error("JSON Parse Error. Raw Text:", text);
        throw new Error(`Failed to parse AI response: ${parseError.message}`);
    }

    // Generate Image
    let imageUrl = null;
    if (data.imagePrompt) {
      console.log("Generating image for prompt:", data.imagePrompt);
      imageUrl = await generateImage(data.imagePrompt, data.slug || "unknown");
    }

    return {
      ...data,
      imageUrl: imageUrl,
      imagePrompt: data.imagePrompt
    } as ProcessedArticle;
  } catch (error: any) {
    console.error("AI Error:", error.message || error);
    
    // Log to SystemLog for debugging
    await logSystem('ERROR', `AI Processing Failed: ${originalTitle.substring(0, 50)}...`, { error: error.message });

    // Special handling for quota issues to inform user
    if (error.message && error.message.includes("429")) {
       console.error("Quota exceeded. Please check your Google Cloud Console billing or rate limits.");
    }

    // Fallback
    return {
      title: originalTitle,
      content: originalContent,
      slug: `error-${Date.now()}`,
      metaDesc: `Error processing (AI Failed): ${error.message || 'Unknown error'}`,
      category: "General",
      qualityScore: 0,
      insight: `Error: AI processing failed. Details: ${error.message}`,
      imageUrl: undefined
    }
  }
}
